# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1978c7ece75c4e49704710f5b2e7dc48e63187acd2194a81c49acb798d972e814df4c309e20974ebfac77066e5bf8f413be83847111de11a42d20445a3c29a30

test:
  secret_key_base: 8771cd3216f0bef0492b256ebe2f1cbd22d2ae6a4a407da8884d0f918f5dd6327b0d856b3aefafe4f33387514affb9ccc63ba8ad0828758046e51678ef2c524c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
